from __future__ import annotations
from typing import Any, ClassVar, overload, Iterable, Iterator, SupportsIndex, Union

_TibsLike = Union["Tibs", "Mutibs", str, bytes, bytearray, memoryview, Iterable[Any]]


class BitIndexing:
    Msb0: ClassVar[BitIndexing]
    Lsb0: ClassVar[BitIndexing]


class Endianness:
    Unspecified: ClassVar[Endianness]
    Big: ClassVar[Endianness]
    Little: ClassVar[Endianness]


class Codec:
    Auto: ClassVar[Codec]
    Raw: ClassVar[Codec]
    Rice: ClassVar[Codec]
    Zstd: ClassVar[Codec]


class Tibs:
    def __init__(self, auto: _TibsLike | None = None, bit_indexing: BitIndexing = BitIndexing.Msb0) -> None: ...

    @property
    def bit_indexing(self) -> BitIndexing: ...

    def to_raw_data(self) -> tuple[bytes, int, int]: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __iter__(self) -> Iterator[bool]: ...

    def chunks(self, chunk_size: int, count: int | None = None) -> Iterator[Tibs]: ...

    def rchunks(self, chunk_size: int, count: int | None = None) -> Iterator[Tibs]: ...

    def __eq__(self, other: Any) -> bool: ...

    def __hash__(self) -> int: ...

    def find_all(self, b: _TibsLike, start: int | None = None, end: int | None = None, byte_aligned: bool = False) -> \
            list[int]: ...

    def find_all_iter(self, b: _TibsLike, start: int | None = None, end: int | None = None,
                      byte_aligned: bool = False) -> Iterator[int]: ...

    def rfind_all_iter(self, b: _TibsLike, start: int | None = None, end: int | None = None,
                  byte_aligned: bool = False) -> Iterator[int]: ...

    def __len__(self) -> int: ...

    @classmethod
    def from_zeros(cls, length: int, /, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Tibs: ...

    @classmethod
    def from_ones(cls, length: int, /, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Tibs: ...

    @classmethod
    def from_string(cls, s: str, /, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Tibs: ...

    @classmethod
    def from_u(cls, u: int, /, length: int, endianness: Endianness = Endianness.Unspecified,
               bit_indexing: BitIndexing = BitIndexing.Msb0) -> Tibs: ...

    def to_u(self, endianness: Endianness = Endianness.Unspecified) -> int: ...

    @classmethod
    def from_i(cls, i: int, /, length: int, endianness: Endianness = Endianness.Unspecified,
               bit_indexing: BitIndexing = BitIndexing.Msb0) -> Tibs: ...

    def to_i(self, endianness: Endianness = Endianness.Unspecified) -> int: ...

    @classmethod
    def from_f(cls, f: float, /, length: int, endianness: Endianness = Endianness.Unspecified,
               bit_indexing: BitIndexing = BitIndexing.Msb0) -> Tibs: ...

    def to_f(self, endianness: Endianness = Endianness.Unspecified) -> float: ...

    @classmethod
    def from_bin(cls, s: str, /, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Tibs: ...

    def to_bin(self) -> str: ...

    @property
    def bin(self) -> str: ...

    @classmethod
    def from_oct(cls, s: str, /, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Tibs: ...

    def to_oct(self) -> str: ...

    @property
    def oct(self) -> str: ...

    @classmethod
    def from_hex(cls, s: str, /, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Tibs: ...

    def to_hex(self) -> str: ...

    @property
    def hex(self) -> str: ...

    @classmethod
    def from_bytes(cls, data: bytes | bytearray | memoryview, /, offset: int | None = None,
                   length: int | None = None, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Tibs: ...

    @classmethod
    def from_bools(cls, iterable: Iterable[Any], /, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Tibs: ...

    @classmethod
    def from_random(cls, length: int, /, secure: bool = False, seed: bytes | bytearray | None = None,
                    bit_indexing: BitIndexing = BitIndexing.Msb0) -> Tibs: ...

    @classmethod
    def from_joined(cls, iterable: Iterable[_TibsLike], /, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Tibs: ...

    @classmethod
    def decode(cls, b: bytes, /) -> Tibs: ...

    def to_bytes(self) -> bytes: ...

    @property
    def bytes(self) -> bytes: ...

    def find(self, b: _TibsLike, start: int | None = None, end: int | None = None,
             byte_aligned: bool = False) -> int | None: ...

    def __contains__(self, b: _TibsLike) -> bool: ...

    def __copy__(self) -> Tibs: ...

    def rfind(self, b: _TibsLike, start: int | None = None, end: int | None = None,
              byte_aligned: bool = False) -> int | None: ...

    def starts_with(self, prefix: _TibsLike) -> bool: ...

    def ends_with(self, suffix: _TibsLike) -> bool: ...

    def count(self, value: Any) -> int: ...

    def all(self) -> bool: ...

    def any(self) -> bool: ...

    def set_at(self, pos: SupportsIndex | Iterable[SupportsIndex] | range) -> Tibs: ...

    def unset_at(self, pos: SupportsIndex | Iterable[SupportsIndex] | range) -> Tibs: ...

    def inverted(self, pos: SupportsIndex | Iterable[SupportsIndex] | None = None) -> Tibs: ...

    def inserted(self, pos: int, bs: _TibsLike, /) -> Tibs: ...

    def replaced(self, old: _TibsLike, new: _TibsLike, start: int | None = None, end: int | None = None,
                 count: int | None = None, byte_aligned: bool = False) -> Tibs: ...

    def rotated_left(self, n: int, start: int | None = None, end: int | None = None) -> Tibs: ...

    def rotated_right(self, n: int, start: int | None = None, end: int | None = None) -> Tibs: ...

    def reversed(self) -> Tibs: ...

    def byte_swapped(self, byte_length: int | None = None) -> Tibs: ...

    def to_mutibs(self) -> Mutibs: ...

    def encode(self, codec: Codec = Codec.Auto) -> bytes: ...

    @overload
    def __getitem__(self, key: SupportsIndex) -> bool: ...

    @overload
    def __getitem__(self, key: slice) -> Tibs: ...

    def __getitem__(self, key: SupportsIndex | slice) -> bool | Tibs: ...

    def __lshift__(self, n: int) -> Tibs: ...

    def __rshift__(self, n: int) -> Tibs: ...

    def __add__(self, bs: _TibsLike) -> Tibs: ...

    def __radd__(self, bs: _TibsLike) -> Tibs: ...

    def __and__(self, bs: _TibsLike) -> Tibs: ...

    def __or__(self, bs: _TibsLike) -> Tibs: ...

    def __xor__(self, bs: _TibsLike) -> Tibs: ...

    def __rand__(self, bs: _TibsLike) -> Tibs: ...

    def __ror__(self, bs: _TibsLike) -> Tibs: ...

    def __rxor__(self, bs: _TibsLike) -> Tibs: ...

    def __invert__(self) -> Tibs: ...

    def __bytes__(self) -> bytes: ...

    def __mul__(self, n: int) -> Tibs: ...

    def __rmul__(self, n: int) -> Tibs: ...

    def __setitem__(self, key: Any, value: Any) -> None: ...

    def __delitem__(self, key: Any) -> None: ...


class Mutibs:
    def __init__(self, auto: _TibsLike | None = None, bit_indexing: BitIndexing = BitIndexing.Msb0) -> None: ...

    @property
    def bit_indexing(self) -> BitIndexing: ...

    @bit_indexing.setter
    def bit_indexing(self, value: BitIndexing) -> None: ...

    def __eq__(self, other: Any) -> bool: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    @classmethod
    def from_string(cls, s: str, /, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Mutibs: ...

    @classmethod
    def from_bin(cls, s: str, /, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Mutibs: ...

    def to_bin(self) -> str: ...

    @property
    def bin(self) -> str: ...

    @classmethod
    def from_oct(cls, s: str, /, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Mutibs: ...

    def to_oct(self) -> str: ...

    @property
    def oct(self) -> str: ...

    @classmethod
    def from_hex(cls, s: str, /, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Mutibs: ...

    def to_hex(self) -> str: ...

    @property
    def hex(self) -> str: ...

    def to_bytes(self) -> bytes: ...

    @property
    def bytes(self) -> bytes: ...

    def to_raw_data(self) -> tuple[bytes, int, int]: ...

    def as_raw_data(self) -> tuple[bytes, int, int]: ...

    @classmethod
    def from_u(cls, u: int, /, length: int, endianness: Endianness = Endianness.Unspecified,
               bit_indexing: BitIndexing = BitIndexing.Msb0) -> Mutibs: ...

    def to_u(self, endianness: Endianness = Endianness.Unspecified) -> int: ...

    @classmethod
    def from_i(cls, i: int, /, length: int, endianness: Endianness = Endianness.Unspecified,
               bit_indexing: BitIndexing = BitIndexing.Msb0) -> Mutibs: ...

    def to_i(self, endianness: Endianness = Endianness.Unspecified) -> int: ...

    @classmethod
    def from_f(cls, f: float, /, length: int, endianness: Endianness = Endianness.Unspecified,
               bit_indexing: BitIndexing = BitIndexing.Msb0) -> Mutibs: ...

    def to_f(self, endianness: Endianness = Endianness.Unspecified) -> float: ...

    @classmethod
    def from_zeros(cls, length: int, /, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Mutibs: ...

    @classmethod
    def from_ones(cls, length: int, /, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Mutibs: ...

    @classmethod
    def from_bools(cls, iterable: Iterable[Any], /, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Mutibs: ...

    @classmethod
    def from_random(cls, length: int, /, secure: bool = False, seed: bytes | bytearray | None = None,
                    bit_indexing: BitIndexing = BitIndexing.Msb0) -> Mutibs: ...

    @classmethod
    def from_bytes(cls, data: bytes | bytearray | memoryview, /, offset: int | None = None,
                   length: int | None = None, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Mutibs: ...

    @classmethod
    def from_joined(cls, iterable: Iterable[_TibsLike], /, bit_indexing: BitIndexing = BitIndexing.Msb0) -> Mutibs: ...

    def __len__(self) -> int: ...

    @overload
    def __getitem__(self, key: SupportsIndex) -> bool: ...

    @overload
    def __getitem__(self, key: slice) -> Mutibs: ...

    def __getitem__(self, key: SupportsIndex | slice) -> bool | Mutibs: ...

    @overload
    def __setitem__(self, key: SupportsIndex, value: Any) -> None: ...

    @overload
    def __setitem__(self, key: slice, value: _TibsLike) -> None: ...

    def __setitem__(self, key: SupportsIndex | slice, value: Any | _TibsLike) -> None: ...

    def __delitem__(self, key: SupportsIndex | slice) -> None: ...

    def starts_with(self, prefix: _TibsLike) -> bool: ...

    def __contains__(self, b: _TibsLike) -> bool: ...

    def ends_with(self, suffix: _TibsLike) -> bool: ...

    def find(self, b: _TibsLike, start: int | None = None, end: int | None = None,
             byte_aligned: bool = False) -> int | None: ...

    def find_all(self, b: _TibsLike, start: int | None = None, end: int | None = None,
                 byte_aligned: bool = False) -> list[int]: ...

    def __and__(self, bs: _TibsLike) -> Mutibs: ...

    def __or__(self, bs: _TibsLike) -> Mutibs: ...

    def __xor__(self, bs: _TibsLike) -> Mutibs: ...

    def __rand__(self, bs: _TibsLike) -> Mutibs: ...

    def __ror__(self, bs: _TibsLike) -> Mutibs: ...

    def __rxor__(self, bs: _TibsLike) -> Mutibs: ...

    def rotate_left(self, n: int, start: int | None = None, end: int | None = None) -> None: ...

    def rotate_right(self, n: int, start: int | None = None, end: int | None = None) -> None: ...

    def rotated_left(self, n: int, start: int | None = None, end: int | None = None) -> Mutibs: ...

    def rotated_right(self, n: int, start: int | None = None, end: int | None = None) -> Mutibs: ...

    @classmethod
    def decode(cls, b: bytes, /) -> Mutibs: ...

    def encode(self, codec: Codec = Codec.Auto) -> bytes: ...

    def set(self, pos: SupportsIndex | Iterable[SupportsIndex] | range) -> None: ...

    def unset(self, pos: SupportsIndex | Iterable[SupportsIndex] | range) -> None: ...

    def set_at(self, pos: SupportsIndex | Iterable[SupportsIndex] | range) -> Mutibs: ...

    def unset_at(self, pos: SupportsIndex | Iterable[SupportsIndex] | range) -> Mutibs: ...

    def count(self, value: Any) -> int: ...

    def all(self) -> bool: ...

    def any(self) -> bool: ...

    def rfind(self, b: _TibsLike, start: int | None = None, end: int | None = None,
              byte_aligned: bool = False) -> int | None: ...

    def invert(self, pos: SupportsIndex | Iterable[SupportsIndex] | None = None) -> None: ...

    def inverted(self, pos: SupportsIndex | Iterable[SupportsIndex] | None = None) -> Mutibs: ...

    def reverse(self) -> None: ...

    def reversed(self) -> Mutibs: ...

    def byte_swap(self, byte_length: int | None = None) -> None: ...

    def byte_swapped(self, byte_length: int | None = None) -> Mutibs: ...

    def __invert__(self) -> Mutibs: ...

    def __lshift__(self, n: int) -> Mutibs: ...

    def __rshift__(self, n: int) -> Mutibs: ...

    def __copy__(self) -> Mutibs: ...

    def to_tibs(self) -> Tibs: ...

    def as_tibs(self) -> Tibs: ...

    def clear(self) -> None: ...

    def capacity(self) -> int: ...

    def reserve(self, additional: int) -> None: ...

    def __add__(self, bs: _TibsLike) -> Mutibs: ...

    def __radd__(self, bs: _TibsLike) -> Mutibs: ...

    def __iadd__(self, bs: _TibsLike) -> Mutibs: ...

    def append(self, bit: bool | int) -> None: ...

    def pop(self) -> bool: ...

    def extend(self, bs: _TibsLike, /) -> None: ...

    def extend_left(self, bs: _TibsLike, /) -> None: ...

    def replace(self, old: _TibsLike, new: _TibsLike, start: int | None = None, end: int | None = None,
                count: int | None = None, byte_aligned: bool = False) -> None: ...

    def replaced(self, old: _TibsLike, new: _TibsLike, start: int | None = None, end: int | None = None,
                 count: int | None = None, byte_aligned: bool = False) -> Mutibs: ...

    def insert(self, pos: int, bs: _TibsLike, /) -> None: ...

    def inserted(self, pos: int, bs: _TibsLike, /) -> Mutibs: ...

    def __ilshift__(self, n: int) -> Mutibs: ...

    def __irshift__(self, n: int) -> Mutibs: ...

    def __bytes__(self) -> bytes: ...

    def __mul__(self, n: int) -> Mutibs: ...

    def __rmul__(self, n: int) -> Mutibs: ...

    def __iter__(self) -> None: ...

    def __iand__(self, bs: _TibsLike) -> Mutibs: ...

    def __ior__(self, bs: _TibsLike) -> Mutibs: ...

    def __ixor__(self, bs: _TibsLike) -> Mutibs: ...

    def __imul__(self, n: int) -> Mutibs: ...
